development:
  adapter: mysql
  database: blog_development
  username: blog
  password: blog

test:
  adapter: mysql
  database: blog_test
  username: blog
  password: blog
  adapter: mysql

production:
  adapter: mysql
  database: blog_production
  username: blog
  password: blog
